package com.growtharchive.domain.meeting;

import com.growtharchive.domain.common.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import java.time.LocalDate;
import java.time.OffsetDateTime;

@Entity
@Table(name = "meetings")
public class Meeting extends BaseEntity {

    @Column(name = "meeting_type", nullable = false, length = 30)
    private String meetingType;

    @Column(nullable = false, length = 120)
    private String title;

    @Column(columnDefinition = "text")
    private String description;

    @Column(name = "meeting_at", nullable = false)
    private OffsetDateTime meetingAt;

    @Column(name = "region_text", nullable = false, length = 120)
    private String regionText;

    @Column(name = "detail_address", columnDefinition = "text")
    private String detailAddress;

    @Column
    private Integer capacity;

    @Column(name = "cost_amount", nullable = false)
    private int costAmount;

    @Column(name = "cover_image_id")
    private Long coverImageId;

    @Column(name = "host_member_id")
    private Long hostMemberId;

    @Column(nullable = false, length = 30)
    private String status;

    @Column(name = "target_month")
    private LocalDate targetMonth;

    @Column(name = "is_auto_generated", nullable = false)
    private boolean autoGenerated;

    @Column(name = "deleted_at")
    private OffsetDateTime deletedAt;

    protected Meeting() {
    }
}
