CREATE TABLE image_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id BIGINT,
    bucket VARCHAR(80) NOT NULL,
    object_key TEXT NOT NULL,
    public_url TEXT,
    image_type VARCHAR(50) NOT NULL,
    mime_type VARCHAR(50) NOT NULL,
    width INT,
    height INT,
    size_bytes BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_image_assets_type CHECK (image_type IN ('PROFILE', 'READING_RECORD', 'MEETING_COVER', 'MEETING_REVIEW'))
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    display_type VARCHAR(20) NOT NULL,
    real_name VARCHAR(50),
    nickname VARCHAR(20) NOT NULL,
    one_line_intro VARCHAR(80) NOT NULL,
    job VARCHAR(50),
    profile_image_id BIGINT,
    kakao_profile_image_url TEXT,
    fifty_year_old_me TEXT NOT NULL,
    join_reason TEXT,
    current_concern TEXT,
    three_year_goal TEXT,
    participation_start_month DATE NOT NULL,
    invite_verified_at TIMESTAMPTZ,
    terms_agreed_at TIMESTAMPTZ,
    privacy_agreed_at TIMESTAMPTZ,
    onboarding_completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deactivated_at TIMESTAMPTZ,
    CONSTRAINT ck_members_role CHECK (role IN ('MEMBER', 'ADMIN')),
    CONSTRAINT ck_members_display_type CHECK (display_type IN ('REAL_NAME', 'NICKNAME')),
    CONSTRAINT ck_members_nickname_length CHECK (char_length(nickname) BETWEEN 2 AND 20),
    CONSTRAINT ck_members_one_line_intro_length CHECK (char_length(one_line_intro) BETWEEN 1 AND 80),
    CONSTRAINT ck_members_fifty_year_old_me_length CHECK (char_length(fifty_year_old_me) BETWEEN 1 AND 1000),
    CONSTRAINT ck_members_join_reason_length CHECK (join_reason IS NULL OR char_length(join_reason) <= 1000),
    CONSTRAINT ck_members_current_concern_length CHECK (current_concern IS NULL OR char_length(current_concern) <= 1000),
    CONSTRAINT ck_members_three_year_goal_length CHECK (three_year_goal IS NULL OR char_length(three_year_goal) <= 1000)
);

ALTER TABLE image_assets
    ADD CONSTRAINT fk_image_assets_owner_member
    FOREIGN KEY (owner_member_id) REFERENCES members (id);

ALTER TABLE members
    ADD CONSTRAINT fk_members_profile_image
    FOREIGN KEY (profile_image_id) REFERENCES image_assets (id);

CREATE UNIQUE INDEX uk_members_nickname ON members (lower(nickname));
CREATE INDEX idx_members_deactivated_at ON members (deactivated_at);
CREATE INDEX idx_members_onboarding_completed_at ON members (onboarding_completed_at);
CREATE INDEX idx_members_participation_start_month ON members (participation_start_month);

CREATE TABLE member_join_intro_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members (id),
    migration_key VARCHAR(100) NOT NULL,
    member_alias VARCHAR(100),
    raw_intro_text TEXT NOT NULL,
    parsed_join_reason TEXT,
    parsed_current_concern TEXT,
    parsed_interests_text TEXT,
    parsed_three_year_goal TEXT,
    source_created_at TIMESTAMPTZ,
    import_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_member_join_intro_sources_status CHECK (import_status IN ('PENDING', 'MAPPED', 'IGNORED', 'FAILED'))
);

CREATE UNIQUE INDEX uk_member_join_intro_sources_migration_key ON member_join_intro_sources (migration_key);
CREATE INDEX idx_member_join_intro_sources_member ON member_join_intro_sources (member_id);
CREATE INDEX idx_member_join_intro_sources_status ON member_join_intro_sources (import_status);

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(100) NOT NULL,
    member_id BIGINT REFERENCES members (id),
    email VARCHAR(255),
    profile_nickname VARCHAR(100),
    profile_image_url TEXT,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_oauth_accounts_provider CHECK (provider IN ('KAKAO'))
);

CREATE UNIQUE INDEX uk_oauth_provider_user ON oauth_accounts (provider, provider_user_id);
CREATE INDEX idx_oauth_member_id ON oauth_accounts (member_id);

CREATE TABLE invite_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash VARCHAR(255) NOT NULL,
    code_preview VARCHAR(30),
    is_active BOOLEAN NOT NULL DEFAULT false,
    created_by_member_id BIGINT REFERENCES members (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deactivated_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uk_invite_codes_single_active ON invite_codes (is_active) WHERE is_active;
CREATE INDEX idx_invite_codes_active ON invite_codes (is_active);

CREATE TABLE interest_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    display_order INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_interest_tags_slug ON interest_tags (slug);
CREATE INDEX idx_interest_tags_active_order ON interest_tags (is_active, display_order);

CREATE TABLE member_interest_tags (
    member_id BIGINT NOT NULL REFERENCES members (id) ON DELETE CASCADE,
    interest_tag_id BIGINT NOT NULL REFERENCES interest_tags (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (member_id, interest_tag_id)
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(30) NOT NULL,
    source_book_id VARCHAR(100),
    isbn10 VARCHAR(20),
    isbn13 VARCHAR(20),
    title VARCHAR(255) NOT NULL,
    authors_text VARCHAR(255) NOT NULL,
    publisher VARCHAR(120),
    published_date DATE,
    thumbnail_url TEXT,
    status VARCHAR(30) NOT NULL,
    created_by_member_id BIGINT REFERENCES members (id),
    source_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_books_source CHECK (source IN ('KAKAO', 'MANUAL', 'NAVER', 'ALADIN')),
    CONSTRAINT ck_books_status CHECK (status IN ('VERIFIED', 'UNVERIFIED'))
);

CREATE INDEX idx_books_title ON books USING gin (to_tsvector('simple', title));
CREATE INDEX idx_books_isbn13 ON books (isbn13);
CREATE INDEX idx_books_status ON books (status);

CREATE TABLE reading_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members (id),
    book_id BIGINT NOT NULL REFERENCES books (id),
    rating SMALLINT,
    one_line_review VARCHAR(300) NOT NULL,
    blog_url TEXT NOT NULL,
    representative_image_id BIGINT REFERENCES image_assets (id),
    status VARCHAR(30) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    hidden_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_reading_records_rating CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reading_records_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED'))
);

CREATE INDEX idx_reading_records_member ON reading_records (member_id, recorded_at DESC);
CREATE INDEX idx_reading_records_book ON reading_records (book_id, recorded_at DESC);
CREATE INDEX idx_reading_records_status ON reading_records (status);
CREATE INDEX idx_reading_records_month ON reading_records ((date_trunc('month', recorded_at AT TIME ZONE 'UTC')));

CREATE TABLE monthly_action_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members (id),
    target_month DATE NOT NULL,
    title VARCHAR(120),
    content TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_monthly_action_plans_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_monthly_action_plans_month CHECK (target_month = date_trunc('month', target_month)::date)
);

CREATE UNIQUE INDEX uk_action_plan_member_month_active
ON monthly_action_plans (member_id, target_month)
WHERE status <> 'DELETED';

CREATE TABLE monthly_reflections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members (id),
    target_month DATE NOT NULL,
    well_done TEXT,
    regret TEXT,
    next_focus TEXT,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_monthly_reflections_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_monthly_reflections_month CHECK (target_month = date_trunc('month', target_month)::date)
);

CREATE UNIQUE INDEX uk_reflection_member_month_active
ON monthly_reflections (member_id, target_month)
WHERE status <> 'DELETED';

CREATE TABLE meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_type VARCHAR(30) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT,
    meeting_at TIMESTAMPTZ NOT NULL,
    region_text VARCHAR(120) NOT NULL,
    detail_address TEXT,
    capacity INT,
    cost_amount INT NOT NULL DEFAULT 0,
    cover_image_id BIGINT REFERENCES image_assets (id),
    host_member_id BIGINT REFERENCES members (id),
    status VARCHAR(30) NOT NULL,
    target_month DATE,
    is_auto_generated BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_meetings_type CHECK (meeting_type IN ('REGULAR_READING', 'REGULAR_ACTION', 'SMALL')),
    CONSTRAINT ck_meetings_status CHECK (status IN ('SCHEDULED', 'HELD', 'CANCELED', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_meetings_capacity CHECK (capacity IS NULL OR capacity > 0),
    CONSTRAINT ck_meetings_cost_amount CHECK (cost_amount >= 0)
);

CREATE INDEX idx_meetings_type_month ON meetings (meeting_type, target_month);
CREATE INDEX idx_meetings_status_at ON meetings (status, meeting_at);
CREATE UNIQUE INDEX uk_regular_meeting_month_type
ON meetings (meeting_type, target_month)
WHERE meeting_type IN ('REGULAR_READING', 'REGULAR_ACTION') AND status <> 'DELETED';

CREATE TABLE meeting_attendances (
    meeting_id BIGINT NOT NULL REFERENCES meetings (id),
    member_id BIGINT NOT NULL REFERENCES members (id),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (meeting_id, member_id),
    CONSTRAINT ck_meeting_attendances_status CHECK (status IN ('JOINED', 'CANCELED'))
);

CREATE TABLE meeting_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES meetings (id),
    member_id BIGINT NOT NULL REFERENCES members (id),
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    representative_image_id BIGINT REFERENCES image_assets (id),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    hidden_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_meeting_reviews_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED'))
);

CREATE INDEX idx_meeting_reviews_meeting ON meeting_reviews (meeting_id, created_at DESC);
CREATE INDEX idx_meeting_reviews_member ON meeting_reviews (member_id, created_at DESC);
CREATE INDEX idx_meeting_reviews_status ON meeting_reviews (status);

CREATE TABLE meeting_review_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_review_id BIGINT NOT NULL REFERENCES meeting_reviews (id),
    image_asset_id BIGINT NOT NULL REFERENCES image_assets (id),
    display_order INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_meeting_review_images_order CHECK (display_order BETWEEN 1 AND 10)
);

CREATE UNIQUE INDEX uk_review_image_order
ON meeting_review_images (meeting_review_id, display_order);

CREATE TABLE recommended_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books (id),
    target_month DATE NOT NULL,
    reason TEXT NOT NULL,
    recommended_by_member_id BIGINT REFERENCES members (id),
    display_order INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_recommended_books_order CHECK (display_order BETWEEN 1 AND 5),
    CONSTRAINT ck_recommended_books_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_recommended_books_month CHECK (target_month = date_trunc('month', target_month)::date)
);

CREATE UNIQUE INDEX uk_recommended_books_month_order
ON recommended_books (target_month, display_order)
WHERE status <> 'DELETED';

CREATE TABLE activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members (id),
    event_type VARCHAR(50) NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    reference_id BIGINT NOT NULL,
    visibility VARCHAR(30) NOT NULL,
    summary VARCHAR(255),
    happened_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_activity_events_visibility CHECK (visibility IN ('PUBLIC', 'MEMBER_ONLY'))
);

CREATE INDEX idx_activity_events_happened_at ON activity_events (happened_at DESC);
CREATE INDEX idx_activity_events_visibility_at ON activity_events (visibility, happened_at DESC);
CREATE INDEX idx_activity_events_member ON activity_events (member_id, happened_at DESC);

CREATE TABLE participation_admin_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_month DATE NOT NULL,
    member_id BIGINT NOT NULL REFERENCES members (id),
    note TEXT,
    created_by_member_id BIGINT NOT NULL REFERENCES members (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_participation_admin_notes_month CHECK (target_month = date_trunc('month', target_month)::date)
);

CREATE UNIQUE INDEX uk_participation_admin_notes_member_month
ON participation_admin_notes (target_month, member_id);

CREATE TABLE admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_member_id BIGINT NOT NULL REFERENCES members (id),
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT,
    before_data JSONB,
    after_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_admin_audit_logs_admin ON admin_audit_logs (admin_member_id, created_at DESC);
CREATE INDEX idx_admin_audit_logs_entity ON admin_audit_logs (entity_type, entity_id);

CREATE OR REPLACE VIEW v_monthly_participation AS
SELECT
    m.id AS member_id,
    m.nickname,
    m.display_type,
    m.real_name,
    m.participation_start_month,
    month_series.target_month,
    EXISTS (
        SELECT 1
        FROM reading_records rr
        WHERE rr.member_id = m.id
          AND rr.status = 'ACTIVE'
          AND date_trunc('month', rr.recorded_at AT TIME ZONE 'UTC')::date = month_series.target_month
    ) AS has_reading_record,
    EXISTS (
        SELECT 1
        FROM monthly_action_plans ap
        WHERE ap.member_id = m.id
          AND ap.status = 'ACTIVE'
          AND ap.target_month = month_series.target_month
    ) AS has_action_plan
FROM members m
CROSS JOIN (
    SELECT generate_series(
        date_trunc('month', now())::date - interval '12 months',
        date_trunc('month', now())::date + interval '1 month',
        interval '1 month'
    )::date AS target_month
) month_series
WHERE m.onboarding_completed_at IS NOT NULL
  AND m.deactivated_at IS NULL
  AND month_series.target_month >= m.participation_start_month;
