INSERT INTO interest_tags (name, slug, display_order, is_active)
VALUES
    ('사업', 'business', 1, true),
    ('창업', 'startup', 2, true),
    ('투자', 'investment', 3, true),
    ('부동산', 'real-estate', 4, true),
    ('독서', 'reading', 5, true),
    ('커리어', 'career', 6, true),
    ('AI', 'ai', 7, true),
    ('개발', 'development', 8, true),
    ('마케팅', 'marketing', 9, true),
    ('운동', 'exercise', 10, true),
    ('건강', 'health', 11, true),
    ('인간관계', 'relationships', 12, true),
    ('경제적 자유', 'financial-freedom', 13, true),
    ('습관', 'habit', 14, true),
    ('러닝', 'running', 15, true),
    ('주식', 'stocks', 16, true),
    ('재테크', 'personal-finance', 17, true),
    ('저축', 'saving', 18, true),
    ('글쓰기', 'writing', 19, true),
    ('리더십', 'leadership', 20, true),
    ('브랜딩', 'branding', 21, true),
    ('사이드프로젝트', 'side-project', 22, true),
    ('명상', 'meditation', 23, true),
    ('수면', 'sleep', 24, true),
    ('식단', 'nutrition', 25, true),
    ('영어', 'english', 26, true),
    ('헬스', 'fitness', 27, true),
    ('요가', 'yoga', 28, true),
    ('등산', 'hiking', 29, true),
    ('수영', 'swimming', 30, true),
    ('마음챙김', 'mindfulness', 31, true),
    ('생산성', 'productivity', 32, true),
    ('시간관리', 'time-management', 33, true),
    ('경제', 'economy', 34, true),
    ('ETF', 'etf', 35, true),
    ('연금', 'pension', 36, true),
    ('절약', 'frugality', 37, true),
    ('세일즈', 'sales', 38, true),
    ('이직', 'job-change', 39, true),
    ('데이터', 'data', 40, true),
    ('디자인', 'design', 41, true),
    ('외국어', 'foreign-language', 42, true),
    ('가족', 'family', 43, true),
    ('육아', 'parenting', 44, true),
    ('여행', 'travel', 45, true),
    ('요리', 'cooking', 46, true),
    ('음악', 'music', 47, true),
    ('사진', 'photography', 48, true),
    ('문화예술', 'arts-culture', 49, true),
    ('철학', 'philosophy', 50, true),
    ('심리학', 'psychology', 51, true),
    ('역사', 'history', 52, true)
ON CONFLICT (slug) DO UPDATE
SET name = excluded.name,
    display_order = excluded.display_order,
    is_active = excluded.is_active;
