package com.growtharchive.service.meeting;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

public record MeetingDetail(
    Long id,
    String meetingType,
    String title,
    String description,
    OffsetDateTime meetingAt,
    String locationRegion,
    String exactLocation,
    Integer capacity,
    Integer feeAmount,
    String coverImageUrl,
    Long hostMemberId,
    String hostDisplayName,
    String status,
    LocalDate targetMonth,
    boolean autoGenerated,
    int attendeeCount,
    boolean attendedByMe,
    boolean canEdit,
    List<String> attendeePreviewImageUrls,
    List<MeetingAttendee> attendees
) {
}
