package com.growtharchive.service.meeting;

import com.growtharchive.exception.ApiException;
import com.growtharchive.exception.ErrorCode;
import com.growtharchive.repository.MeetingRepository;
import com.growtharchive.security.AccessLevel;
import com.growtharchive.security.AccessLevelCalculator;
import com.growtharchive.security.CurrentMemberResolver;
import com.growtharchive.security.MemberPrincipal;
import jakarta.servlet.http.HttpServletRequest;
import java.time.OffsetDateTime;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class MeetingService {

    private final CurrentMemberResolver currentMemberResolver;
    private final AccessLevelCalculator accessLevelCalculator;
    private final MeetingRepository meetingRepository;

    public MeetingService(
        CurrentMemberResolver currentMemberResolver,
        AccessLevelCalculator accessLevelCalculator,
        MeetingRepository meetingRepository
    ) {
        this.currentMemberResolver = currentMemberResolver;
        this.accessLevelCalculator = accessLevelCalculator;
        this.meetingRepository = meetingRepository;
    }

    public List<MeetingSummary> list(String type, int page, int size) {
        int boundedSize = Math.min(Math.max(size, 1), 50);
        return meetingRepository.findPublic(normalizeTypeFilter(type), boundedSize, Math.max(page, 0) * boundedSize);
    }

    public List<MeetingSummary> adminList(HttpServletRequest request, String type, int page, int size) {
        currentMemberResolver.require(request, AccessLevel.ADMIN);
        int boundedSize = Math.min(Math.max(size, 1), 100);
        return meetingRepository.findAdmin(normalizeTypeFilter(type), boundedSize, Math.max(page, 0) * boundedSize);
    }

    public MeetingDetail adminDetail(HttpServletRequest request, Long meetingId) {
        currentMemberResolver.require(request, AccessLevel.ADMIN);
        return detail(request, meetingId);
    }

    public MeetingDetail detail(HttpServletRequest request, Long meetingId) {
        MemberPrincipal viewer = currentMemberResolver.resolveOptional(request);
        AccessLevel accessLevel = accessLevelCalculator.calculate(viewer);
        boolean memberView = accessLevelCalculator.hasAtLeast(accessLevel, AccessLevel.MEMBER);
        MeetingDetail detail = meetingRepository.findById(meetingId, !memberView, viewer == null ? null : viewer.memberId())
            .orElseThrow(() -> new ApiException(ErrorCode.MEETING_NOT_FOUND));
        if (!memberView) {
            return new MeetingDetail(
                detail.id(),
                detail.meetingType(),
                detail.title(),
                detail.description(),
                detail.meetingAt(),
                detail.locationRegion(),
                null,
                detail.capacity(),
                detail.feeAmount(),
                detail.coverImageUrl(),
                detail.hostMemberId(),
                null,
                detail.status(),
                detail.targetMonth(),
                detail.autoGenerated(),
                detail.attendeeCount(),
                false,
                false,
                detail.attendeePreviewImageUrls(),
                List.of()
            );
        }
        return new MeetingDetail(
            detail.id(),
            detail.meetingType(),
            detail.title(),
            detail.description(),
            detail.meetingAt(),
            detail.locationRegion(),
            detail.exactLocation(),
            detail.capacity(),
            detail.feeAmount(),
            detail.coverImageUrl(),
            detail.hostMemberId(),
            detail.hostDisplayName(),
            detail.status(),
            detail.targetMonth(),
            detail.autoGenerated(),
            detail.attendeeCount(),
            detail.attendedByMe(),
            detail.canEdit(),
            detail.attendeePreviewImageUrls(),
            meetingRepository.findAttendees(meetingId)
        );
    }

    @Transactional
    public MeetingDetail createSmall(HttpServletRequest request, MeetingCommand command) {
        MemberPrincipal member = currentMemberResolver.require(request, AccessLevel.MEMBER);
        MeetingCommand normalized = normalize(command, false);
        Long meetingId = meetingRepository.createSmall(member.memberId(), normalized);
        return detail(request, meetingId);
    }

    @Transactional
    public MeetingDetail updateSmall(HttpServletRequest request, Long meetingId, MeetingCommand command) {
        MemberPrincipal member = currentMemberResolver.require(request, AccessLevel.MEMBER);
        MeetingDetail existing = meetingRepository.findEditableById(meetingId)
            .orElseThrow(() -> new ApiException(ErrorCode.MEETING_NOT_FOUND));
        if (!"SMALL".equals(existing.meetingType())) {
            throw new ApiException(ErrorCode.FORBIDDEN, "소소모임만 이 경로에서 수정할 수 있습니다.");
        }
        if (existing.hostMemberId() == null || !existing.hostMemberId().equals(member.memberId())) {
            throw new ApiException(ErrorCode.FORBIDDEN, "소소모임 생성자만 수정할 수 있습니다.");
        }
        meetingRepository.updateSmall(meetingId, normalize(command, false));
        return detail(request, meetingId);
    }

    @Transactional
    public MeetingDetail updateRegular(HttpServletRequest request, Long meetingId, MeetingCommand command) {
        currentMemberResolver.require(request, AccessLevel.ADMIN);
        MeetingDetail existing = meetingRepository.findEditableById(meetingId)
            .orElseThrow(() -> new ApiException(ErrorCode.MEETING_NOT_FOUND));
        if ("SMALL".equals(existing.meetingType())) {
            throw new ApiException(ErrorCode.FORBIDDEN, "Admin은 소소모임 내용을 직접 수정할 수 없습니다.");
        }
        meetingRepository.updateRegular(meetingId, normalize(command, true));
        return detail(request, meetingId);
    }

    @Transactional
    public MeetingDetail join(HttpServletRequest request, Long meetingId) {
        MemberPrincipal member = currentMemberResolver.require(request, AccessLevel.MEMBER);
        MeetingDetail meeting = meetingRepository.findEditableById(meetingId)
            .orElseThrow(() -> new ApiException(ErrorCode.MEETING_NOT_FOUND));
        if (!"SCHEDULED".equals(meeting.status())) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR, "예정된 모임만 참석할 수 있습니다.");
        }
        if (!meetingRepository.isJoined(meetingId, member.memberId())
            && meeting.capacity() != null
            && meeting.capacity() > 0
            && meetingRepository.joinedCount(meetingId) >= meeting.capacity()) {
            throw new ApiException(ErrorCode.MEETING_CAPACITY_FULL);
        }
        meetingRepository.join(meetingId, member.memberId());
        return detail(request, meetingId);
    }

    @Transactional
    public MeetingDetail cancel(HttpServletRequest request, Long meetingId) {
        MemberPrincipal member = currentMemberResolver.require(request, AccessLevel.MEMBER);
        meetingRepository.findEditableById(meetingId)
            .orElseThrow(() -> new ApiException(ErrorCode.MEETING_NOT_FOUND));
        meetingRepository.cancel(meetingId, member.memberId());
        return detail(request, meetingId);
    }

    @Transactional
    public void hide(HttpServletRequest request, Long meetingId) {
        currentMemberResolver.require(request, AccessLevel.ADMIN);
        ensureExists(meetingId);
        meetingRepository.hide(meetingId);
    }

    @Transactional
    public void restore(HttpServletRequest request, Long meetingId) {
        currentMemberResolver.require(request, AccessLevel.ADMIN);
        ensureExists(meetingId);
        meetingRepository.restore(meetingId);
    }

    @Transactional
    public void deleteByAdmin(HttpServletRequest request, Long meetingId) {
        currentMemberResolver.require(request, AccessLevel.ADMIN);
        ensureExists(meetingId);
        meetingRepository.delete(meetingId);
    }

    @Transactional
    public void deleteByCreator(HttpServletRequest request, Long meetingId) {
        MemberPrincipal member = currentMemberResolver.require(request, AccessLevel.MEMBER);
        MeetingDetail existing = meetingRepository.findEditableById(meetingId)
            .orElseThrow(() -> new ApiException(ErrorCode.MEETING_NOT_FOUND));
        if (!"SMALL".equals(existing.meetingType()) || existing.hostMemberId() == null || !existing.hostMemberId().equals(member.memberId())) {
            throw new ApiException(ErrorCode.FORBIDDEN, "소소모임 생성자만 삭제할 수 있습니다.");
        }
        meetingRepository.delete(meetingId);
    }

    private void ensureExists(Long meetingId) {
        meetingRepository.findEditableById(meetingId).orElseThrow(() -> new ApiException(ErrorCode.MEETING_NOT_FOUND));
    }

    private MeetingCommand normalize(MeetingCommand command, boolean allowStatus) {
        String title = required(command.title(), "모임명을 입력해 주세요.");
        String region = required(command.locationRegion(), "지역 수준 장소를 입력해 주세요.");
        OffsetDateTime meetingAt = command.meetingAt();
        if (meetingAt == null) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR, "모임 일시를 입력해 주세요.");
        }
        Integer capacity = command.capacity();
        if (capacity != null && capacity <= 0) {
            capacity = null;
        }
        Integer feeAmount = command.feeAmount() == null ? 0 : command.feeAmount();
        if (feeAmount < 0) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR, "비용은 0원 이상이어야 합니다.");
        }
        String status = allowStatus ? normalizeStatus(command.status()) : "SCHEDULED";
        return new MeetingCommand(
            title,
            trimToNull(command.description()),
            meetingAt,
            region,
            trimToNull(command.exactLocation()),
            capacity,
            command.thumbnailImageId(),
            feeAmount,
            status
        );
    }

    private String normalizeStatus(String status) {
        String value = status == null || status.isBlank() ? "SCHEDULED" : status.trim();
        if (!List.of("SCHEDULED", "HELD", "CANCELED", "HIDDEN", "DELETED").contains(value)) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR, "모임 상태를 확인해 주세요.");
        }
        return value;
    }

    private String normalizeTypeFilter(String type) {
        if (type == null || type.isBlank()) {
            return null;
        }
        if (!List.of("REGULAR_READING", "REGULAR_ACTION", "SMALL").contains(type)) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR, "모임 유형을 확인해 주세요.");
        }
        return type;
    }

    private String required(String value, String message) {
        String normalized = trimToNull(value);
        if (normalized == null) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR, message);
        }
        return normalized;
    }

    private String trimToNull(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }
}
